name: Docker Image Build and Push

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/javeke-ws-dev:$(cat VERSION) .
      - name: Login to Docker Hub
        run: docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_TOKEN }}'
      - name: Push image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/javeke-ws-dev:'$(cat VERSION)'