name: Docker Image Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo chmod +x mvnw
      - name: Clears build cache
        run: sudo ./mvnw clean
      - name: Generate JAR file
        run: sudo ./mvnw -Dspring.mongodb.embedded.version=${{ secrets.MONGODB_VERSION }} package
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/javeke-ws:$(cat VERSION) .
      - name: Login to Docker Hub
        run: docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_TOKEN }}'
      - name: Push image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/javeke-ws:$(cat VERSION)
